### ISSUE TITLE
Add rules around disabling rules

### ISSUE THREAD

**Issue by Haroenv** [algolia/eslint-config-algolia#112]
* [`eslint-comments/no-unlimited-disable`](https://mysticatea.github.io/eslint-plugin-eslint-comments/rules/no-unlimited-disable.html)

Some of our build scripts have errors in them that were suppressed by fully disabling the rules

* [`no-unused-disable`](https://mysticatea.github.io/eslint-plugin-eslint-comments/rules/no-unused-disable.html)

In `npm-search` there were some unused disables that I didn't immediately find, having this will make our code simpler

Looking at that, I think we should enable all rules (except stylistic) for eslint-plugin-eslint-comments

**Comment by dispix** [comment]
I think that makes a lot of sense!

**Comment by Haroenv** [comment]
Note there's also https://eslint.org/docs/user-guide/command-line-interface#--report-unused-disable-directives, but it doesn't go as far for restricting disables.
