### ISSUE TITLE
Configuration for rule "@typescript-eslint/array-type" is invalid

### ISSUE THREAD

**Issue by sarahdayan** [algolia/eslint-config-algolia#113]
I got the following error when trying to lint my project with `'algolia/typescript'`:

```
Error: .eslintrc.js » eslint-config-algolia/typescript » ./rules/typescript.js:
        Configuration for rule "@typescript-eslint/array-type" is invalid:
        Value "array-simple" should be object.
```

Here's my config:

```
// .eslintrc.js

module.exports = {
  extends: 'algolia/typescript'
}
```

And relevant dependency versions:

- `babel-eslint`: `^10.0.2`
- `eslint`: `^6.1.0`
- `eslint-config-algolia`: `^13.4.0`
- `eslint-config-prettier`: `^6.0.0`
- `eslint-plugin-import`: `^2.18.2`
- `eslint-plugin-jest`: `^22.15.1`
- `eslint-plugin-prettier`: `^3.1.0`
- `prettier`: `^1.18.2`

I'll try to investigate later, but thought I'd file this in case someone wants to give it a spin.

**Comment by Haroenv** [comment]
I think it is because we didn't update the typescript plugin yet in InstantSearch, see https://github.com/typescript-eslint/typescript-eslint/pull/654. In InstantSearch.js we are at v1.13.0 of the plugin. The PR there implies a breaking change in 2.0.0

**Comment by Haroenv** [comment]
**temporary solution**: use `typescript-eslint@1.13.0` until this issue is closed

**Comment by Haroenv** [comment]
you can now use `eslint-config-algolia@14` with `typescript-eslint@2`
