### ISSUE TITLE
no-unused-expression is kind of too strict

### ISSUE THREAD

**Issue by redox** [algolia/eslint-config-algolia#2]
I'm used to do conditional invocations like:

```js
tryThat() || doThat();
// or
ensureThat() && doThat();
```

I find it very readable but it's currently not allowed, what do you think?

**Comment by Jerskouille** [comment]
I'm not found of it, because of the implicit use of `== true`.
With `===` it would then become:
```js
(tryThat() === false) && doThat();
// or
(ensureThat() === true) && doThat();
```
which I find less readable than
```js
if (tryThat() === false)
  doThat();
// or
if (ensureThat() === true) // This would be even better if `ùnless` existed in JS
  do That()
```

I'm not sure our configuration allows it, but even one lines if seem more readable to me than the first one:
```js
if (tryThat() === false) doThat();
// or
if (ensureThat() === true) doThat();
```

**Comment by vvo** [comment]
Not against it (disabling the rule). @Jerskouille thanks for pointing the `== true` coercion.

But this is also true with `cond && otherCond` without even invoking a fn.

Still if we know what we are doing and if it really bothers you @redox we can update this rule, PR?!:)

**Comment by redox** [comment]
First wanted to have your POV. I'm used to read (& write) code with such constructions. @bobylito @pixelastic, what do you think?

**Comment by bobylito** [comment]
I'm open to improvement here. I don't think I use this kind of code structure. Right now I think I would probably prefer the more explicit version that uses if (as @Jerskouille proposed but without the need to explicitly uses ===, or only for non boolean equality)

**Comment by pixelastic** [comment]
(I'll post a longer answer later) 

I don't really like constructs that use && and || for testing conditions and executing methods in Javascript. 

I'm OK with that in bash or using the handy one liners in ruby, but I think if (condition) { doStuff() } is more javascripty

**Comment by redox** [comment]
And do you use `obj.attr = obj.attr || defaultValue` ?

**Comment by pixelastic** [comment]
Actually, yes I do it for easy default assignment

**Comment by bobylito** [comment]
> And do you use `obj.attr = obj.attr || defaultValue` ?

but this is not unused :)

**Comment by pixelastic** [comment]
I'm ok with @bobylito and @Jerskouille. I'd rather have explicit `if` statements than `tryFoo() && doBar()`. This explicitly shows what is a condition and what is an execution

**Comment by redox** [comment]
:+1: Fair enough for me!
