### ISSUE TITLE
Our rules are no longer applied

### ISSUE THREAD

**Issue by Haroenv** [algolia/eslint-config-algolia#33]
Things like `no-unused-vars` don't get flagged anymore. Is this because of it's ordered before prettier, or that the import there doesn't work like that? 

related: algolia/react-instantsearch#59

**Comment by vvo** [comment]
Indeed there's something weird here, we are using https://github.com/prettier/eslint-config-prettier rules to override our own. That should definitely not disable those as you can see from the prettier files. There's something else.

**Comment by vvo** [comment]
Ok I think I know why

**Comment by Haroenv** [comment]
Yes, that works now
