### ISSUE TITLE
Remove Jest plugin from base

### ISSUE THREAD

**Issue by rayrutjes** [algolia/eslint-config-algolia#39]
I'm working on a small plugin for Atom, and I don't use Jest.
Can I disable that plugin when extending the algolia config?
Otherwise could we remove that plugin from base config?

**Comment by rayrutjes** [comment]
From looking at other "base" configs, it looks like plugins are never included.
We should probably only push our coding rules, and let users specify the desired plugins.
WDYT?

**Comment by pixelastic** [comment]
Same comment here. When reading the instruction I don't understand why I would need Jest for basic formatting.

**Comment by vvo** [comment]
Works for me to have a separate extends: algolia/jest for people willing to write tests with Jest (which should be the go-to solution at Algolia as soon as you need to write tests and there's no pre-bundled testing solution in your project, like atom plugins)

**Comment by vvo** [comment]
= Accepting PR

**Comment by rayrutjes** [comment]
Thanks @Haroenv ❤️
