### ISSUE TITLE
activate no-magic-numbers?

### ISSUE THREAD

**Issue by vvo** [algolia/eslint-config-algolia#48]
https://eslint.org/docs/rules/no-magic-numbers

I feel like in most situations you do want to activate this to enforce clear semantics in code.

For example:

```js
statusCodeType = const statusFamily = Math.floor(statusCode / 100);
if (statusCodeType === 3) redirect();
```

VS

```js
statusCodeType = const statusFamily = Math.floor(statusCode / 100);
if (statusCodeType === STATUSES_REDIRECTS) redirect();
```

WDYT?

**Comment by Haroenv** [comment]
seems like with that rule the `100` would also need to be replaced?

I'd say `ignoreArrayIndexes` should be `true` as well

**Comment by vvo** [comment]
> seems like with that rule the 100 would also need to be replaced?

I wondered that too

**Comment by iam4x** [comment]
If it does replace the '100' here I don't think it's a good idea, it will be a real pain for any math operation:

```
const DIVIDE_BY_TWO = 2;

function handleValue(result) {
  return result / DIVIDE_BY_TWO;
}
```

**Comment by vvo** [comment]
> const DIVIDE_BY_TWO = 2;
> 
> function handleValue(result) {
>   return result / DIVIDE_BY_TWO;
> }

Yes clearly we don't want that, I think those are not taken into account, we will investigate

**Comment by francoischalifour** [comment]
There's an `ignore` option that allows to add number exceptions in an array. `2` could be an exception for instance.

However, I think this is too much work for not enough value.

**Comment by Haroenv** [comment]
Yes, seems like this is a good idea in theory, but there are just a lot of numbers that aren't really magic that would show up as magic.

**Comment by francoischalifour** [comment]
Agreed! Let's close this.

We can reopen if ever we face any issues with magic numbers.
