### ISSUE TITLE
Add angular rules

### ISSUE THREAD

**Issue by vvo** [algolia/eslint-config-algolia#81]
In the same spirit of Vue support, could we support Angular in our eslint? I have no idea what's necessary, any hint @iam4x?

**Comment by iam4x** [comment]
The tooling for TypeScript is different, we use another tool called `tslint` and with this config:

```json
{
  "extends": [
    "tslint-config-airbnb",
    "tslint-config-prettier"
  ],
  "rulesDirectory": [
    "tslint-plugin-prettier"
  ],
  "rules": {
    "prettier": true,
    "no-submodule-imports": false,
    "import-name": false
  },
  "cliOptions": {
    "exclude": [
      "node_modules",
      "dist"
    ]
  }
}
```

We could maybe create a `tsling-config-algolia` for every TypeScript projects at Algolia? (cc @alexandremeunier @proudlygeek @JonasBa)
