### ISSUE TITLE
consider adding eslint-plugin-promise

### ISSUE THREAD

**Issue by Haroenv** [algolia/eslint-config-algolia#82]
Since we work a lot with promises and async code, [these](https://github.com/xjamundx/eslint-plugin-promise) rules seem to be nice to avoid common pitfalls

**Comment by vvo** [comment]
Do you have a code example or PR where this would be helpful in our current stack? Just looking at obvious things this where the plugin would help us. Thanks

**Comment by Haroenv** [comment]
Will update when I have an idea. I just saw the plugin and was interested :)
